name: CI/CD Pipeline for Express App

on:
  push:
    branches:
      - main # Trigger only on main branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Trigger Render Deployment
        if: success()
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d185s695pdvs73btc7ag?key=gCv0d1LQC5Q"
